import{b as i}from"./shared/browser-polyfill.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const m=document.getElementById("status"),c=document.getElementById("scrapeBtn"),l=document.getElementById("result"),u=document.getElementById("error");i.tabs.query({active:!0,currentWindow:!0}).then(o=>{const e=o[0];if(!(e!=null&&e.id)||!e.url){a("Open a ChatGPT or Claude conversation first.","unsupported");return}const s=new URL(e.url).hostname;s==="chatgpt.com"||s==="chat.openai.com"?(a("✓ ChatGPT detected — ready to scrape","detected"),c.disabled=!1):s==="claude.ai"?(a("✓ Claude detected — ready to scrape","detected"),c.disabled=!1):a("Navigate to ChatGPT or Claude to scrape a conversation.","unsupported")});c.addEventListener("click",async()=>{c.disabled=!0,c.textContent="Scraping...",u.style.display="none",l.style.display="none";try{const[o]=await i.tabs.query({active:!0,currentWindow:!0});if(!(o!=null&&o.id))throw new Error("No active tab");const e=await i.tabs.sendMessage(o.id,{type:"SCRAPE_CONVERSATION"});if(!e.success)throw new Error(e.error||"Scraping failed");const{conversation:r}=e;if(!r)throw new Error("No conversation data returned");l.innerHTML=`
      <div>
        <strong class="title">${p(r.title)}</strong><br>
        <span class="count">${r.messages.length}</span> messages from 
        <strong>${r.source}</strong>
      </div>
      <div class="actions">
        <button class="btn-sm" id="copyBtn">📋 Copy JSON</button>
        <button class="btn-sm" id="downloadBtn">💾 Download</button>
        <button class="btn-sm" id="saveBtn">☁️ Save</button>
      </div>
    `,l.style.display="block",document.getElementById("copyBtn").addEventListener("click",()=>{navigator.clipboard.writeText(JSON.stringify(r,null,2)),document.getElementById("copyBtn").textContent="✓ Copied!"}),document.getElementById("downloadBtn").addEventListener("click",()=>{const s=new Blob([JSON.stringify(r,null,2)],{type:"application/json"}),t=URL.createObjectURL(s),n=document.createElement("a");n.href=t,n.download=`${r.source}_${Date.now()}.json`,n.click(),URL.revokeObjectURL(t)}),document.getElementById("saveBtn").addEventListener("click",async()=>{const s=await i.runtime.sendMessage({type:"SAVE_CONVERSATION",conversation:r});s!=null&&s.success&&(document.getElementById("saveBtn").textContent="✓ Saved!")}),c.textContent="Scrape Again",c.disabled=!1}catch(o){const e=o.message;u.textContent=e,u.style.display="block",c.textContent="Scrape This Conversation",c.disabled=!1}});function a(o,e){m.textContent=o,m.className=`status ${e}`}function p(o){const e=document.createElement("div");return e.textContent=o,e.innerHTML}
